# Generated by Django 4.0.10 on 2024-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
