# Generated by Django 4.0.10 on 2024-10-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=140)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.news')),
            ],
        ),
    ]
