# Generated by Django 4.0.10 on 2024-10-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_comment_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_name',
            new_name='profile_name',
        ),
    ]
