# Generated by Django 4.0.10 on 2024-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_comment_name_comment_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
