# Generated by Django 4.0.10 on 2024-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
